# See https://docs.minecraftforge.net/en/1.21.x/gettingstarted/modfiles/#modstoml
# There are lots of things you can do with the mods.toml, and not all fields are included with this MDK
# References: https://github.com/MinecraftForge/MDKExamples

modLoader="javafml"
loaderVersion="[64,)"
license="${mod_license}"
issueTrackerURL="https://github.com/ChloePrime/KubeJS-CSV/issues/" #optional
#clientSideOnly=true #optional, default=false

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
#updateJSONURL="https://example.com/updates.json" #optional
displayURL="https://github.com/ChloePrime/KubeJS-CSV/" #optional
logoFile="logo.png" #optional
credits='''${mod_credits}''' #optional
authors="${mod_authors}" #optional
displayTest="IGNORE_ALL_VERSION" #optional, default=MATCH_VERSION when not clientSideOnly, else IGNORE_ALL_VERSION

description='''${mod_description}'''

[[dependencies.${mod_id}]] #recommended
    modId="forge"
    mandatory=true
    versionRange="[64,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]] #recommended
    modId="minecraft"
    mandatory=true
    versionRange="[26.1,26.2)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]] #recommended
    modId="kubejs"
    mandatory=true
    versionRange="${kubejs_version_range}"
    ordering="NONE"
    side="BOTH"
